# Generated by Django 6.0 on 2025-12-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_chatbot_con_user_id_72ef78_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chatbot_mes_convers_0cc130_idx',
        ),
    ]
