# Generated by Django 6.0 on 2025-12-25 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_unique_active_conversation_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('mentioned_topics', models.JSONField(default=dict, help_text="Topics user has discussed: {'boxing': 5, 'school': 3, 'family': 2} (frequency count)")),
                ('mentioned_people', models.JSONField(default=dict, help_text="People in user's life: {'mom': True, 'friend': True, 'teacher': True}")),
                ('mentioned_places', models.JSONField(default=dict, help_text="Places user goes: {'school': True, 'gym': True, 'home': True}")),
                ('mentioned_activities', models.JSONField(default=dict, help_text="Activities user does: {'boxing': True, 'gaming': True, 'studying': True}")),
                ('common_emotions', models.JSONField(default=dict, help_text="Emotions user frequently expresses: {'sadness': 3, 'anxiety': 2}")),
                ('recurring_problems', models.JSONField(default=list, help_text="Problems user talks about repeatedly: ['bullying', 'body image']")),
                ('communication_style', models.CharField(default='casual', help_text="User's preferred communication style: casual, formal, brief, detailed", max_length=20)),
                ('typical_session_length', models.IntegerField(default=0, help_text='Average number of messages per conversation')),
                ('last_topics_discussed', models.JSONField(default=list, help_text="Most recent 10 topics user mentioned: ['boxing', 'food', 'weather']")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Memory',
                'verbose_name_plural': 'User Memories',
                'indexes': [models.Index(fields=['user'], name='chatbot_use_user_id_97cd42_idx'), models.Index(fields=['-updated_at'], name='chatbot_use_updated_0a9eeb_idx')],
            },
        ),
    ]
