# Generated by Django 6.0 on 2025-12-28 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_usermemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=20)),
                ('messages_remaining', models.IntegerField(default=20)),
                ('reset_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_half', models.BooleanField(default=False)),
                ('notified_three', models.BooleanField(default=False)),
                ('notified_zero', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Limit',
                'verbose_name_plural': 'Message Limits',
                'db_table': 'message_limits',
            },
        ),
    ]
