# Generated by Django 6.0 on 2025-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_messagelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemory',
            name='first_conversation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermemory',
            name='last_conversation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagelimit',
            name='messages_remaining',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='messagelimit',
            name='total_messages',
            field=models.IntegerField(default=15),
        ),
    ]
