# Generated by Django 6.0 on 2025-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_usermemory_first_conversation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='messagelimit',
            name='id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='messagelimit',
            name='ml_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='chatbot_conversation',
        ),
        migrations.AlterModelTable(
            name='message',
            table='chatbot_message',
        ),
        migrations.AlterModelTable(
            name='messagelimit',
            table='chatbot_messagelimit',
        ),
    ]
