# Generated by Django 4.2.27 on 2026-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_conversation_id_remove_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_media_message',
            field=models.BooleanField(default=False, help_text='True if this message contains media content'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_data',
            field=models.JSONField(blank=True, default=dict, help_text='Media metadata: video IDs, URLs, titles, etc.'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, help_text="Type of media: 'video' or 'image'", max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_media_message'], name='chatbot_mes_is_medi_e0012a_idx'),
        ),
    ]
