# Generated by Django 6.0 on 2025-12-26 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(help_text='User feedback message', max_length=1000)),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot or image', null=True, upload_to='feedback_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when feedback was submitted')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for spam prevention (not displayed)', null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
