# Generated by Django 6.0 on 2025-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ip_address_hash',
            field=models.CharField(blank=True, help_text='Hashed IP address for spam prevention (privacy-friendly, cannot be reversed)', max_length=64, null=True),
        ),
    ]
