# Generated by Django 6.0 on 2025-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_ip_address_feedback_ip_address_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ip_address_hash',
            field=models.CharField(blank=True, help_text='Hashed IP address for spam prevention', max_length=64, null=True),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback_feedback',
        ),
    ]
