# Generated by Django 4.2.27 on 2025-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_id_feedback_feedback_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Flagged if suspicious patterns detected'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when feedback was submitted'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional screenshot or image (processed and sanitized)', null=True, upload_to='feedback_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ip_address_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hashed IP address for spam prevention (SHA-256)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='User feedback message (sanitized)', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='feedback_fe_created_a1f280_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['ip_address_hash', '-created_at'], name='feedback_fe_ip_addr_ff6c23_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_suspicious', '-created_at'], name='feedback_fe_is_susp_d82d87_idx'),
        ),
    ]
