# Generated by Django 6.0 on 2025-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistory',
            name='id',
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='ph_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='passwordhistory',
            table='accounts_passwordhistory',
        ),
    ]
